- name: configuring catalogue server
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: Disable the default nodejs module
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: Install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present
  
  - name: create app directory
    ansible.builtin.file:  # create a directory for the application
     path: /app
     state: directory

  - name: add system user
    ansible.builtin.user: # create a system user for the application
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: download catalogue code
    ansible.builtin.get_url: # download the catalogue code from the remote repository
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip

  - name: unzip catalogue code
    ansible.builtin.unarchive: # extract or unzip the downloaded zip file to the application directory
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes # this means the source file is already on the remote catalogue server

  - name: install dependencies
    community.general.npm:  # install the npm required node.js dependencies for the application
      path: /app

  - name: Copy catalogue service file
    ansible.builtin.copy: # copy the systemd service file for the catalogue application
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.services

  - name: daemon reload
    ansible.builtin.systemd_service: # daemon reload to recognize the new service file
    daemon_reload: true

  - name: start and enable catalogue
    ansible.builtin.service: # start and enable the catalogue service
      name: catalogue
      state: started
      enabled: true

  - name: copy mongo repo
    ansible.builtin.copy: # copy the MongoDB repository file to the yum repository directory
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb
    ansible.builtin.dnf:  # install the MongoDB server package
      name: mongodb-mongosh
      state: present

  - name: check products loaded or not # check if the 'catalogue' database exists in MongoDB
    ansible.builtin.command: mongosh --host mongodb.devops84.shop --eval 'db.getMongo().getDBNames().indexOf("catalogue")' # this command returns the index of the 'catalogue' database in the list of databases
    register: catalogue_output

  - name: print catalogue output # debug task to print the output of the previous command
    ansible.builtin.debug:  # this will show the index of the 'catalogue' database, -1 means it does not exist
      msg: "{{ catalogue_output }}"

  - name: load products
    ansible.builtin.shell: mongosh --host mongodb.devops84.shop < /app/db/master-data.js
    when: catalogue_output.stdout | int < 0