- name: configuration frontend server
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: Disable the default nodejs module
    ansible.builtin.command: dnf module disable nginx -y
  
  - name: enable nginx
    ansible.builtin.command: dnf module enable nginx:1.24 -y

  - name: install nginx
    ansible.buildin.dnf:
      name: nginx
      state: present
  
  - name: enable and start nginx
    ansible.buildin.service:
      name: nginx
      state: started
      enabled: yes