- name: mysql configuration
  hosts: mysql
  become: true
  tasks:
    - name: Install MySQL Server
      ansible.builtin.dnf:
        name: mysql-server
        state: installed

    - name: enable and start MySQL service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: set root password
      ansible.builtin.command:  mysql_secure_installation --set-root-pass RoboShop@1