- name: mysql configuration
  hosts: local
  connection: local
  become: true
  tasks:
    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present
      tags: install

    - name: Start MySQL Service
      service:
        name: mysql
        state: started
        enabled: true

    - name: Copy MySQL Configuration File
      template:
        src: my.cnf.j2
        dest: /etc/mysql/my.cnf
      notify:
        - Restart MySQL Service
      tags: config

  handlers:
    - name: Restart MySQL Service
      service:
        name: mysql
        state: restarted