- name: configuration shipping server
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install rabbitmq server
    ansible.builtin.dnf:
      name: rabbitmq-server
      state: installed

  - name: enable and start rabbitmq service
    ansible.builtin.service:
      name: rabbitmq
      state: started
      enabled: yes

  - name: create rabbitmq user
    community.rabbitmq.rabbitmq_user:
      user: roboshop
      password: roboshop123
       permissions:
        - vhost: /
          configure_priv: .*
          read_priv: .*
          write_priv: .*
      state: present