- name: configuring user server
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: Disable the default nodejs module
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: Install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: create app directory
    ansible.builtin.file:  # create a directory for the application
      path: /app
      state: directory

  - name: add system user
    ansible.builtin.user: # create a system user for the application
      name: roboshop
      shell: /sbin/nologin
      home: /app
      system: true

  - name: download user code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
      dest: /tmp/user.zip
  
  - name: unzip user code
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes # this means the source file is already on the remote user server

  - name: install dependencies
    community.general.npm:  # install the npm required node.js dependencies for the application
    path: /app

  - name: Copy user service file
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: systemctl daemon reload
    ansible.builtin.systemd_server: # daemon reload to recognize the new service file
      daemon_reload: true

  - name: start and enable user
    ansible.builtin.service:
      name: user
      state:started
      enable: yes